default_platform :ios

platform :ios do
    desc "Setting dependencies and building app without tests"
    lane :build_for_testing do
      cocoapods
      scan(
        scheme: "ChatApp",
        clean: true,
        devices: ["iPhone 12 Pro"]
      )
    end
  
    desc "Run tests on built app"
    lane :run_tests_without_building do
      cocoapods
      scan(
        scheme: "ChatApp",
        devices: ["iPhone 12 Pro"]
      )
    end
  
    desc "Both build app and run tests"
    lane :build_and_run_tests do
      build_for_testing
      run_tests_without_building
    end
end