default_platform :ios
app_name = "ChatApp"
repo_url = "https://github.com/rdscoo1/ChatApp/"
author_name = "Roman Khodukin"
icon_url = "https://github.com/rdscoo1/ChatApp/blob/main/ChatApp/Supporting%20Files/Resources/Assets.xcassets/LaunchScreen/AppLogoLaunchScreen.imageset/AppLogo.pdf"
webhook_url = ENV['DISCORD_NOTIFIER_WEBHOOK_URL']

platform :ios do
    desc "Setting dependencies and building app without tests"
    lane :build_for_testing do
      cocoapods
      scan(
        scheme: "ChatApp",
        clean: true,
        devices: ["iPhone 12 Pro"]
      )
    end
  
    desc "Run tests on built app"
    lane :run_tests_without_building do
      cocoapods
      scan(
        scheme: "ChatApp",
        devices: ["iPhone 12 Pro"]
      )
    end
  
    desc "Both build app and run tests"
    lane :build_and_run_tests do
      build_for_testing
      run_tests_without_building
      discord_notification
    end


    desc "Discord Notification"
    lane :discord_notification do
      discord_notifier(
        webhook_url: webhook_url,
        title: "Build report of ChatApp",
        description: "Success"
      )
    end

end